set lines=50
set columns=161
colorscheme wombat

" Copy and paste
vmap <C-c> y:call system("pbcopy", getreg("\""))<CR>
"nmap <C-v> :call setreg("\"",system("pbpaste"))<CR>p

" no toolbar
set guioptions-=T

" no blinking cursor
set guicursor+=a:blinkon0

" font
set guifont=Monaco:h12

" remove all default menus
aunmenu *

" add custom menu options
menu Edit.Paste "*p
menu Style.Tabs-8 :set noexpandtab tabstop=8 shiftwidth=8<CR>
menu Style.Spaces-8 :set expandtab tabstop=8 shiftwidth=8<CR>
menu Style.Tabs-4 :set noexpandtab tabstop=4 shiftwidth=4<CR>
menu Style.Spaces-4 :set expandtab tabstop=4 shiftwidth=4<CR>
menu Style.Tabs-2 :set noexpandtab tabstop=2 shiftwidth=2<CR>
menu Style.Spaces-2 :set expandtab tabstop=2 shiftwidth=2<CR>
